run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 25
  goconst:
    min-len: 3
    min-occurrences: 3
  depguard:
    rules:
      main:
        deny:
          - pkg: "io/ioutil"
            desc: "io/ioutil is deprecated since Go 1.19"
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/neilsmahajan/vocabulary_study_go_cli

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - goimports
    - gofmt
    - misspell
    - depguard

issues:
  exclude-use-default: true
  exclude-dirs:
    - vendor
  exclude-files:
    - ".*\\.pb\\.go$"
  max-issues-per-linter: 0
  max-same-issues: 0
